### ISSUE TITLE
RPC Method with formurlmaintaincase

### ISSUE THREAD

**Issue by matthewroach** [OpenBD/openbd-core#12]
If you are using RPC calls with access type remote and you have the bluedragon setting: `<formurlmaintaincase>true</formurlmaintaincase>` the method of the CFC has to be passed in as uppercase. But if you do not have the formurlmaintaincase setting at all you can call the remote function with method lowercase.

```
<cffunction name="run" access="remote" returntype="struct" returnformat="JSON">
    <cfreturn { test: 1 } />
</cffunction>
```

Calling the above function with `<formurlmaintaincase>true</formurlmaintaincase>` using `rpc/test.cfc?method=run` throws `the request must contain a METHOD parameter`

Calling the above function using `rpc/test.cfc?METHOD=run` is successful

If you do not have the `<formurlmaintaincase>true</formurlmaintaincase>` setting you can successful call the rpc using both:

```
rpc/test.cfc?METHOD=run
rpc/test.cfc?method=run
```

**Comment by wua22** [comment]
I've committed a fix. Give the nightly build a shot.
