### ISSUE TITLE
Issue with cfschedule

### ISSUE THREAD

**Issue by thenitai** [OpenBD/openbd-core#2]
Just found another issue with cfschedule and delete. I can create any schedule with cfschedule, however using delete or pause doesn't work.

```
<cfschedule action="delete" task="razscheduleduploadevent[71787786-d1eb-4498-84c4b686aa3786de]" />
```

It doesn't throw an error at all, but simply ignores delete or pause. Restarted the engine and still doesn't work.

**Comment by a1anw2** [comment]
are you loading the bluedragon.xml remotely by any chance?  If you are, then the delete etc won't work

**Comment by thenitai** [comment]
No, not remote. All local.

On Wed, Apr 8, 2015 at 3:44 PM, Alan Williamson notifications@github.com
wrote:

> are you loading the bluedragon.xml remotely by any chance? If you are,
> then the delete etc won't work
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenBD/openbd-core/issues/2#issuecomment-91057802.

## 

See for yourself how easy it is to manage files today. Join the revolution!

Razuna - Hosted Digital Asset Management Solution
http://www.razuna.com/

Razuna - Open Source Digital Asset Management
http://www.razuna.org/

Twitter - http://twitter.com/razunahq
Support Platform - http://help.razuna.com

**Comment by a1anw2** [comment]
mm okay i can't recreate this.   I have used this:

```
<!---
<cfschedule
    action="update"
    task="testone"
    startdate="01/01/2014"
    enddate="01/01/2016"
    STARTTIME="00:00:00"
    url="http://google.com"
    file="/tmp/#GetTickCount()#.html"
    interval="daily"
    >
--->

<cfschedule
    action="delete"
    task="testone"
    >
```

and it worked as expected.

**Comment by thenitai** [comment]
Not sure, but it doesn't work here with the latest build. Also, I use the
task name as posted on here. Might that be an issue?

On Wed, Apr 8, 2015 at 6:01 PM, Alan Williamson notifications@github.com
wrote:

> mm okay i can't recreate this. I have used this:
> 
> 
> 
> <cfschedule
>     action="delete"
>     task="testone"
>     >
> 
> and it worked as expected.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenBD/openbd-core/issues/2#issuecomment-91081557.

## 

See for yourself how easy it is to manage files today. Join the revolution!

Razuna - Hosted Digital Asset Management Solution
http://www.razuna.com/

Razuna - Open Source Digital Asset Management
http://www.razuna.org/

Twitter - http://twitter.com/razunahq
Support Platform - http://help.razuna.com

**Comment by a1anw2** [comment]
It might be actually ... though it should be just a string.  I will do some testing with that.

**Comment by thenitai** [comment]
Ok thanks.

On Thu, Apr 9, 2015 at 6:11 AM, Alan Williamson notifications@github.com
wrote:

> It might be actually ... though it should be just a string. I will do some
> testing with that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenBD/openbd-core/issues/2#issuecomment-91227442.

## 

See for yourself how easy it is to manage files today. Join the revolution!

Razuna - Hosted Digital Asset Management Solution
http://www.razuna.com/

Razuna - Open Source Digital Asset Management
http://www.razuna.org/

Twitter - http://twitter.com/razunahq
Support Platform - http://help.razuna.com

**Comment by a1anw2** [comment]
@thenitai i have tested it with the razscheduleduploadevent[71787786-d1eb-4498-84c4b686aa3786de] task name, but it still works as expected.

What bit isn't working for you?  how do you know it isn't deleting for you?  If i run it, i see it being removed from the bluedragon.xml and i see, if i do a action=listall (see below) it is no longer there too.

```
<cfschedule
    action="listall"
    result="r"  >
<cfdump var="#r#">
```

if you can narrow down a case then re-open this please.

**Comment by wua22** [comment]
Please ignore that commit ^. It was really against #2 in the openbd-manual.
