### ISSUE TITLE
Incorrect line number when debugging cfscript

### ISSUE THREAD

**Issue by standayweb** [OpenBD/openbd-core#27]
When there is an error in a cfscript tag it just shows the line number of the start of the cfscript tag, it should display the actual line of cfscript that it errored on.

**Comment by wua22** [comment]
Can you help me reproduce this? Any cfscript error I've seen includes the line number within the tag.

**Comment by standayweb** [comment]
After speaking with Matt about this, I believe there was an onError function showing custom error output and not outputting line numbers properly so looks like this is probably a non-issue.
