### ISSUE TITLE
QueryRun result missing generatedkey

### ISSUE THREAD

**Issue by AaronJWhite** [OpenBD/openbd-core#29]
I am running a recent nightly (build date: 2016-04-16 04:04:43 GMT), but the result variable given back does not contain the generatedkey value. This should be pretty easy to reproduce. Let me know if I have to make a test case.

**Comment by wua22** [comment]
What database and version of that db are you querying against?

**Comment by AaronJWhite** [comment]
MySQL version 5.5.32.

**Comment by wua22** [comment]
Got it. Fix committed.
