### ISSUE TITLE
returnformat in cfscript not working

### ISSUE THREAD

**Issue by AaronJWhite** [OpenBD/openbd-core#30]
I am running a recent nightly (build date: 2016-04-16 04:04:43 GMT). Using the returnformat attribute on cfscript functions does not seem to work. Not sure why/how this bug keeps coming back.

example:

``` coldfusion
<cfcomponent output="false">
<cfscript>
public struct function WhyNoReturnJson()
    returnformat="JSON"
{
   var response = {success:false,id:0,msg: "-_-"};
   return response;
}
</cfscript>
</cfcomponent>
```

**Comment by AaronJWhite** [comment]
Hi guys. Is this not an issue?

**Comment by wua22** [comment]
The returnformat attribute only applies when the caller is remote. If you were to change the access type of the function in your example to remote, you'll see that the returnformat is adhered to.

**Comment by AaronJWhite** [comment]
Makes perfect sense. Thank you for getting back to me. Would it be possible or make sense for OpenBD to provide a "warning" for such a thing? If OpenBD notices a function using the returnformat attribute, but is not using remote then throw a silent warning to the log or console? Again, not necessary, but wondering if the OpenBD team every considered warning-like messages. Thanks.

**Comment by wua22** [comment]
I think we did at one point but the overhead/effort vs developer benefit didn't make sense for us to implement it.
