### ISSUE TITLE
GetMetadata doesn't return function information for script only components

### ISSUE THREAD

**Issue by alexskinner** [OpenBD/openbd-core#4]
Take the following test.cfc

```
component {
    function get() {
        return false;
    }
}
```

If I call via this

a=new test();
writedump(getmetadata(a));

No function information is returned

If the component is replaced with

```
<cfcomponent>
<cfscript>
    function get() {
        return false;
    }
</cfscript>
</cfcomponent>
```

Then my call is rerun the metadata sees the information as expected. Came across this in my efforts to get the latest Taffy Rest API working with Open BD.

**Comment by a1anw2** [comment]
I will take a look.  We officially don't support the 'component { }' syntax quite yet.  That is a pure side-effect of something else we were experimenting with.
