### ISSUE TITLE
Upgrading from old OpenBD, odd Json in the old version?

### ISSUE THREAD

**Issue by MFernstrom** [OpenBD/openbd-core#48]
We're upgrading an old server to the latest OpenBD and as we go we found that there is old json data (still in use) that has CFML style YES/NO instead of json True/False in the json data, causing the newer OpenBD deserializer to fail with Invalid Json.

Is this expected? Was there an old version which used yes/no for json booleans?

**Comment by wua22** [comment]
I see what happened here.

That functionality is dependent on a customization we made to the Jackson library but that was effectively removed when we upgraded Jackson in this commit https://github.com/OpenBD/openbd-core/commit/06633c8a9aad62d98d4d8db61301d3666f6f9144.

**Comment by MFernstrom** [comment]
Aha I see, was that removed on purpose or just forgotten to be added to the new version of Jackson?

**Comment by wua22** [comment]
Just forgotten. I'll aim to get that added back in this week.

**Comment by MFernstrom** [comment]
That's great, thanks @wua22

**Comment by wua22** [comment]
I've committed a fix for that and rebuilt the nightly build.

**Comment by MFernstrom** [comment]
You rock @wua22, is the modified version the latest Jackson? (Just curious)

**Comment by wua22** [comment]
No I just went with the same version that we had in jar form to keep things simple.

**Comment by MFernstrom** [comment]
Oh ok, cool. Looks like it's working, thanks again Andy!
