### ISSUE TITLE
cfcontent Remote S3 gives Internal Server Error

### ISSUE THREAD

**Issue by matthewroach** [OpenBD/openbd-core#7]
When using the new `cfcontent` with the remote attribute with s3. If the s3 file no longer exists an Internal Server Error is given

```
com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey;
```

**Comment by a1anw2** [comment]
Good catch, i will return 404 when not available.
