### ISSUE TITLE
CFHTTP and CFIMAGE

### ISSUE THREAD

**Issue by LiQz0r** [OpenBD/openbd-core#72]
Hey,

I use `<cfhttp url="someUrl" result="result" method="GET" timeout="60" getAsBinary="yes">` to get an image from Azure (stored as a BLOB) because I have to provide some headers using `<cfhttpparam>` to get access to the image.

Using regular ColdFusion (from Adobe) I'm able to display the image like so:
`<cfset myImage = ImageNew("#result.filecontent#")/>`
`<cfimage source="#myImage#" action="writeToBrowser"/>`

If I provide the `srcfile` attribute that OpenBD expects instead of `source` this results in an error saying "Data not supported".

Is there any way to display a BLOB as an image directly in the browser?

**Comment by dtsw** [comment]
What is your code now?
Have you tried the function CharsetEncode() on the BLOB data?
or sometimes if you use quotes around BLOB, it does not work, but it would without quotes.

Regards,
Oliver

**Comment by MFernstrom** [comment]
Take a look at the image functions http://openbd.org/manual/?/function/category/image maybe there's something here you can use?

Maybe grab data, convert to base64 image, and display that?

**Comment by LiQz0r** [comment]
Thanks to both of you for your replies!

I ended up using using MFernstrom's method:
`<cfset myImage = ImageNew(#result.filecontent#)/>`
`<cfset base64Image = ImageWriteBase64(name = #myImage#, format="jpg", inhtmlformat = true)/>`
`<img src="<cfoutput>#base64Image#</cfoutput>"/>`

Where `#result.filecontent#` is the BLOB returned from Azure by using `<cfhttp>`.
