### ISSUE TITLE
What happened to www.openbd.org?

### ISSUE THREAD

**Issue by dpbabcock** [OpenBD/openbd-core#85]
I am a long time fan of openbd. Was shocked when I went to openbd.org and was redirected here. What's going on? Checked the Google Group. Nothing there.

Is Openbd going the way of the dinosaur? I hope not.

**Comment by MFernstrom** [comment]
Looks like a new page/site is being developed and redirecting here in the meantime

**Comment by dpbabcock** [comment]
I hope so. The old site was very good. OpenBD makes a GREAT quick and easy docker container for building API's and all manner of small web apps. I run it with an Alpine linux/Java base image and it is compact (200 mb or so) and performant running on Docker. Because it's containerized I can put it anywhere.
 THANKS for the update.

**Comment by wua22** [comment]
There has been very little development on OpenBD in years. The www site was outdated so it was time to retire it.

**Comment by MFernstrom** [comment]
That's fair, but I use the Manual all the time to look up functions.

**Comment by dpbabcock** [comment]
The other issue is that the site provided easy access to three different versions, the desktop, Ready to Run, and a Tomcat web app. My fav was "Ready to Run" and it would be really nice to have the "recipe" used to build these here. So far, I can't get the ant build to work downloading what is here on GitHub. 

The bigger question is, is there any continuing stewardship of openbd or is it just being cast adrift for those still interested?

**Comment by wua22** [comment]
@MFernstrom  the manual is open source so it's easy enough to run up locally - https://github.com/OpenBD/openbd-manual

@dpbabcock Github is setup to build releases so you don't really need to build with Ant. You'll find them here: https://github.com/OpenBD/openbd-core/releases

**Comment by dpbabcock** [comment]
Thanks Andy! I had completely missed the releases section. Might be good to put something in the README to highlight that is where you can find the complete builds as there were on the original website. Keep up the good work. I really like open-bd and it is my “goto” for quick containerized web services/apps in docker. MUCH smaller than the Lucee image at only about a fourth the size.

-dB
