### ISSUE TITLE
OpenBD Ajax sending set Connection and Content-Length caues Chrome/Safari to block call.

### ISSUE THREAD

**Issue by minifiredragon** [OpenBD/openbd-core#9]
Webkit blocks any attempt to set the Connection and Content-Length headers via XMLHttpRequest. 

Refused to set unsafe header "Content-length"blueDragonAjaxLibrary.load @ load.cfres?js=cfajaxproxy01.js:1remoteCall @ load.cfres?js=cfc2211656215.js:1keepActive @ load.cfres?js=cfc2211656215.js:1stayConnected @ main.js:62

Refused to set unsafe header "Connection"blueDragonAjaxLibrary.load @ load.cfres?js=cfajaxproxy01.js:1remoteCall @ load.cfres?js=cfc2211656215.js:1keepActive @ load.cfres?js=cfc2211656215.js:1stayConnected @ main.js:62

Anyway to override inside the app?

**Comment by a1anw2** [comment]
Sadly this is an issue with the browser side and little we can do here.

**Comment by minifiredragon** [comment]
How about not setting them at all?  Maybe I am reading things wrong, but in the web standards those 2 headers are not suppose to be set.
